server:
  port: 8072
spring:
#  main:
#    web-application-type: reactive
  application:
    name: gatewayserver
# Learning-only: actuator shutdown endpoint
# Do NOT enable in production
management:
  endpoints:
    web:
      exposure:
        include: busrefresh, info, health, gateway, refresh, env
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
#      routeDefinitionsLocator:
#        enabled: true
      enabled: true
    env:
      enabled: true
#    config:
#      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG